### ISSUE TITLE
播放中点击暂停，进入列表页再返回播放页面，播放进度状态消失

### ISSUE THREAD

**Issue by willerfu** [Edge00/react-music-player#1]
码主可以测试下这个bug，有什么好方法可以解决浏览器返回后，数据读取正常。

**Comment by Edge00** [comment]
@willerfu 谢谢关注！
出现这个问题的原因是每次切换路由时，`player.js`中的`Player`类里面的construtor会执行，并初始化state：
```
  constructor(props) {
    super(props),
    this.state = {
      progress: 0,
      volume: 0,
      isPlay: true,
      leftTime: ''
    }
  }
```
解决办法：
1. 可以将state实时存储在localStorage内，在componentWillMount时读取localStorage并setState。
2. 提升状态，将Player的state提升到index.js中，这样就可以避免在player加载的时候state被初始化。
